### ISSUE TITLE
微调的训练数据怎么准备？

### ISSUE THREAD

**Issue by zhangjh** [LlamaFamily/Llama2-Chinese#280]
供微调使用的训练数据一定要是：
```"text"
"<s>Human: 给出一个问题，要求助手回答该问题的时间限制。如果回答超出时间限制，客户应该得到通知。
问题: ""一天有多少秒？""时间限制: 10秒
</s><s>Assistant: 一天有86400秒。
</s>"
```
这样的格式吗？
现在已有一批自有数据，如果必须要组装成这种格式，成本也太大了点。。
首先必须要整理出QA的形式，其次还得花费巨大的人力投入去改造成这种特有的格式。

**Comment by ZHangZHengEric** [comment]
是的，确实需要整理出qa 的形式。希望的少量的qa 让模型具备泛化能力。除非场景不需要对话，得看场景

**Comment by zhangjh** [comment]
这。。数据量太大那不是没有可行性了？不可能从大量的业务内容文本中整理出一条条的QA来。
我试过用Base Model+Vector Embedding的形式可以做到，但是还是想试下训练出专有模型的这条路。看来是行不通了。。
